baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'multi embed player documents'

theme = 'lotusdocs'
enableRobotsTXT = true

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
